AgroApp/Controllers/StateMasterController.cs
using AgroApp.Common;
using AgroApp.Data;
using Common;
using Entities;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace AgroApp.Controllers
{
    public class StateMasterController : Controller
    {
        #region Context Object
        // Entity Context
        AgroAppEntities context = new AgroAppEntities();
        #endregion


        // GET: StateMaster
        public async Task<ActionResult> Index()
        {
            return View();
        }
      

        #region State
        public async Task<ActionResult> StateRead([DataSourceRequest]DataSourceRequest request,string str)
        {
            try
            {
                var stateId=0;
                if(str==null)
                {
                    str = "";
                }
                var StateIdParam = new SqlParameter
                {
                    ParameterName = "StateId",
                    DbType = DbType.Int32,
                    Value = stateId
                };
                var StringParam = new SqlParameter
                {
                    ParameterName = "String",
                    DbType = DbType.String,
                    Value = str
                };
                List<StateMasterModel.State> model = new List<StateMasterModel.State>();
                
                model = context.Database.SqlQuery<StateMasterModel.State>("Sp_StateMaster_GetAllState @StateId,@String", StateIdParam,StringParam).ToList();


                return Json(model.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
            }

            catch (Exception ex)
            {
                return Json(new { Message = CommonHelper.GetErrorMessage(ex), IsError = Convert.ToString((int)Enums.NotifyType.Error) }, JsonRequestBehavior.AllowGet);
            }


        }

        [HttpPost]
        public async Task<ActionResult> StateSave([DataSourceRequest] DataSourceRequest request, StateMasterModel.State model)
        {
            string message = string.Empty;
            int result = 0;
            try
            {
                var StateIdParam = new SqlParameter
                {
                    ParameterName = "StateId",
                    DbType = DbType.Int32,
                    Value = model.StateId
                };
                var StateNameParam = new SqlParameter
                {
                    ParameterName = "StateName",
                    DbType = DbType.String,
                    Value = model.StateName
                };

                var IsActiveParam = new SqlParameter
                {
                    ParameterName = "IsActive",
                    DbType = DbType.Boolean,
                    Value = model.IsActive
                };

                 result = context.Database.SqlQuery<int>("SP_StateMaster_StateInsertUpdate @StateId,@StateName,@IsActive",StateIdParam,StateNameParam,IsActiveParam).FirstOrDefault();

               
            }
            catch (Exception ex)
            {
                message = CommonHelper.GetErrorMessage(ex);
            }
           
            return Json(new { id = result}, JsonRequestBehavior.AllowGet);
        }
        public async Task<ActionResult> StateDestroy([DataSourceRequest] DataSourceRequest request, int? stateId)
        {
            string message = string.Empty;
            try
            {
                var StateIdParam = new SqlParameter
                {
                    ParameterName = "StateId",
                    DbType = DbType.Int32,
                    Value = (object)stateId ?? DBNull.Value
                };

                int result = context.Database.SqlQuery<int>("SP_StateMaster_DeleteState @StateId", StateIdParam).FirstOrDefault();
                if (result == 1)
                {
                    message = "State Deleted SucessFully !!! ";
                }
                else if (result == 0)
                {
                    message = "State Deleted Failed !  Try After Some Time!!! ";
                }
                return (result == 0)
                 ? Json(new { Message = message, IsError = Convert.ToString((int)Enums.NotifyType.Error) }, JsonRequestBehavior.AllowGet)
                : Json(new { Message = message, IsError = Convert.ToString((int)Enums.NotifyType.Success) }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Message = message, IsError = Convert.ToString((int)Enums.NotifyType.Error) }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult StateWindowOpen(int? stateId)
        {
            StateMasterModel.State model = new StateMasterModel.State();
            if (stateId>0)
            {
                var StateIdParam = new SqlParameter
                {
                    ParameterName = "StateId",
                    DbType = DbType.Int32,
                    Value = stateId
                };
                model = context.Database.SqlQuery<StateMasterModel.State>("Sp_StateMaster_GetAllState @StateId", StateIdParam).FirstOrDefault();
            }
            
            return PartialView("_StateAddEdit",model);
        }
        #endregion

        #region District
        public async Task<ActionResult> DistRead([DataSourceRequest]DataSourceRequest request, string strDist)
        {
            try
            {
                var distId = 0;
                List<StateMasterModel.District> model = new List<StateMasterModel.District>();
                var DistIdParam = new SqlParameter
                {
                    ParameterName = "DistId",
                    DbType = DbType.Int32,
                    Value = distId
                };
                var StringDistParam = new SqlParameter
                {
                    ParameterName = "StringDist",
                    DbType = DbType.String,
                    Value = strDist
                };
                model = context.Database.SqlQuery<StateMasterModel.District>("Sp_DistMaster_GetAllDist @DistId,@StringDist", DistIdParam,StringDistParam).ToList();


                return Json(model.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
            }

            catch (Exception ex)
            {
                return Json(new { Message = CommonHelper.GetErrorMessage(ex), IsError = Convert.ToString((int)Enums.NotifyType.Error) }, JsonRequestBehavior.AllowGet);
            }
        }
        [HttpPost]
        public async Task<ActionResult> DistSave([DataSourceRequest] DataSourceRequest request, StateMasterModel.District model)
        {
            string message = string.Empty;
            int result = 0;
            try
            {
                var DistIdParam = new SqlParameter
                {
                    ParameterName = "DistId",
                    DbType = DbType.Int32,
                    Value = model.DistId
                };
                var StateIdParam = new SqlParameter
                {
                    ParameterName = "StateId",
                    DbType = DbType.Int32,
                    Value = model.StateId
                };
                var DistNameParam = new SqlParameter
                {
                    ParameterName = "DistName",
                    DbType = DbType.String,
                    Value = model.DistName
                };

                var IsActiveParam = new SqlParameter
                {
                    ParameterName = "IsActive",
                    DbType = DbType.Boolean,
                    Value = model.DistIsActive
                };

                result = context.Database.SqlQuery<int>("SP_DistrictMaster_DistrictInsertUpdate @DistId,@StateId,@DistName,@IsActive", DistIdParam, StateIdParam, DistNameParam, IsActiveParam).FirstOrDefault();


            }
            catch (Exception ex)
            {
                message = CommonHelper.GetErrorMessage(ex);
            }
            //return Json(new[] { model }.ToDataSourceResult(request));
            return Json(new { id = result }, JsonRequestBehavior.AllowGet);
        }
        public async Task<ActionResult> DistDestroy([DataSourceRequest] DataSourceRequest request, int? distId)
        {
            string message = string.Empty;
            try
            {
                var DistIdParam = new SqlParameter
                {
                    ParameterName = "DistId",
                    DbType = DbType.Int32,
                    Value = (object)distId ?? DBNull.Value
                };

                int result = context.Database.SqlQuery<int>("SP_DistMaster_DleteDistrict @DistId", DistIdParam).FirstOrDefault();
                if (result == 1)
                {
                    message = "District Deleted SucessFully !!! ";
                }
                else if (result == 0)
                {
                    message = "District Deleted Failed !  Try After Some Time!!! ";
                }
                return (result == 0)
                 ? Json(new { Message = message, IsError = Convert.ToString((int)Enums.NotifyType.Error) }, JsonRequestBehavior.AllowGet)
                : Json(new { Message = message, IsError = Convert.ToString((int)Enums.NotifyType.Success) }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { Message = message, IsError = Convert.ToString((int)Enums.NotifyType.Error) }, JsonRequestBehavior.AllowGet);
            }
        }
        public async Task< ActionResult> DistWindowOpen(int? distId)
        {
            StateMasterModel.District model = new StateMasterModel.District();
            if (distId > 0)
            {
                var str1 = "";

AgroApp/Views/StateMaster/_DistrictAddEdit.cshtml
@using Kendo.Mvc.UI

@using Common;
@model Entities.StateMasterModel.District

@{
    Layout = null;
}

@using (Html.BeginForm(null, null, FormMethod.Post, new { @id = "DistForm" }))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(m => m.DistId)
    <div class="k-edit-form-container">

        <div class="row">
            @Html.LabelFor(model => model.DistName, htmlAttributes: new { @class = "editor-label" })
            <div class="editor-field">
                @(Html.Kendo().TextBoxFor(m => m.DistName))
                @Html.ValidationMessageFor(model => model.DistName, "", new { @class = "text-danger" })

            </div>

            @Html.LabelFor(model => model.StateName, htmlAttributes: new { @class = "editor-label" })
            <div class="editor-field">
                @*@(Html.Kendo().TextBoxFor(m => m.StateName))*@
                @*@(Html.Kendo().ComboBoxFor(m => m.StateId).HtmlAttributes(new { @style = "width: 100%" })
        .DataTextField("Name")
           .DataValueField("Id")
           .DataSource(source =>
           {
               source.Read(read =>
               {
                   read.Action("GetStateList", "Common");
               });
           })
         .Placeholder("-- Select --"))*@
                @(Html.Kendo().DropDownListFor(m => m.StateId)
                    .OptionLabel("Select Satate")
                    .HtmlAttributes(new { id = "CountryId", style = "width:100%;" })
                    .DataTextField("Name")
                    .DataValueField("Id")
                    .DataSource(source =>
                    {
                        source.Read(read =>
                        {
                            read.Action("GetStateList", "Common");
                        });
                    })
                    //Events(e => e.Change("onCountryChange").DataBound("onCountryBound"))
                    )
                
               
                @Html.ValidationMessageFor(model => model.StateName, "", new { @class = "text-danger" })

            </div>
            @Html.LabelFor(model => model.DistIsActive, htmlAttributes: new { @class = "editor-label" })
            <div class="editor-field">
                @(Html.Kendo().CheckBoxFor(m => m.DistIsActive))
                @Html.ValidationMessageFor(model => model.DistIsActive, "", new { @class = "text-danger" })
            </div>
            <div class="k-edit-buttons">

                <input type="button" value="SAVE" class="k-button k-button-icontext k-primary" onclick="DistSave();" />
                <input type="button" value="CANCEL" class="k-button k-button-icontext" onclick="ClosePopup();" />
            </div>
        </div>
    </div>
}

<script>

       function DistSave() {
            debugger
           var validator = $('#DistForm').kendoValidator().data("kendoValidator");
        if (validator.validate()) {
            var url = '@Url.Action("DistSave", "StateMaster")';
            var paramValue = $('#DistForm').serialize();
            callwebservice(url, paramValue, saveCompleted, false, datatypeEnum.json, typeEnum.post);
            return true;
        }
        return false;
    }
    function ClosePopup() {
        closeKendoWindow("Dist");
    }
    function saveCompleted(returString) {
        
        debugger
        if (returString.id ==1) {
            ClosePopup();
            $('#gridDist').data('kendoGrid').dataSource.read();
            ShowSuccessMessage("District Saved SucessFully!!!");
        }
        else if (returString.id == 2) {
            ClosePopup();
            $('#gridDist').data('kendoGrid').dataSource.read();
            ShowSuccessMessage("District Updated SucessFully!!!");

        }
        else {
            ClosePopup();
            ShowErrorMessage("District Already Exist !!!");
        }

    }
</script>

AgroApp/Views/StateMaster/_StateAddEdit.cshtml
@using Kendo.Mvc.UI

@using Common;
@model Entities.StateMasterModel.State

@{
    Layout = null;
}

@using (Html.BeginForm(null, null, FormMethod.Post, new { @id = "StateForm" }))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(m=>m.StateId)
    <div class="k-edit-form-container">

        <div class="row">
            @Html.LabelFor(model => model.StateName, htmlAttributes: new { @class = "editor-label" })
            <div class="editor-field">
                @(Html.Kendo().TextBoxFor(m => m.StateName))
                @Html.ValidationMessageFor(model => model.StateName, "", new { @class = "text-danger" })

            </div>

            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "editor-label" })
            <div class="editor-field">
                @(Html.Kendo().CheckBoxFor(m => m.IsActive))
                @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
            </div>
            <div class="k-edit-buttons">

                <input type="button" value="SAVE" class="k-button k-button-icontext k-primary" onclick="return StateSave();" />
                <input type="button" value="CANCEL" class="k-button k-button-icontext" onclick="ClosePopup();" />
            </div>
        </div>
    </div>
}

<script>

      function StateSave() {
            debugger
          var validator = $('#StateForm').kendoValidator().data("kendoValidator");
        if (validator.validate()) {
            var url = '@Url.Action("StateSave", "StateMaster")';
            var paramValue = $('#StateForm').serialize();
            callwebservice(url, paramValue, saveCompleted, false, datatypeEnum.json, typeEnum.post);
            return true;
        }
        return false;
    }
    function ClosePopup() {
        closeKendoWindow("State");
    }
    function saveCompleted(returString) {
        
        debugger
        if (returString.id ==1) {
            ClosePopup();
            $('#gridState').data('kendoGrid').dataSource.read();
            ShowSuccessMessage("State Saved SucessFully!!!");
        }
        else if (returString.id == 2) {
            ClosePopup();
            $('#gridState').data('kendoGrid').dataSource.read();
            ShowSuccessMessage("State Updated SucessFully!!!");

        }
        else {
            ClosePopup();
            ShowErrorMessage("StateName Already Exist !!!");
        }

    }
</script>